version: '3'

services:
  web:
    build: ./docker/web
    ports:
    - 80:80
    volumes:
    - ./:/var/www/html
    depends_on:
    - mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8080:80"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kamitter
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: always
    ports:
    - 3306:3306
    volumes:
    - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
